### ISSUE TITLE
Ingredient category presentation format options

### ISSUE THREAD

**Issue by filipecarneiro** [filipecarneiro/ELabel#19]
Currently, the ingredient category is presented between parentheses, after the ingredient.

> Grapes, Tirage liqueur, Expedition liqueur, Preservative (Sulphites), Stabiliser (Carboxymethylcellulose)

**Describe the solution you'd like**
Use colons instead of brackets. 

> Grapes, Tirage liqueur, Expedition liqueur, Preservative: Sulphites, Stabiliser: Carboxymethylcellulose

**Additional context**
The list of ingredients shall be headed or preceded by a suitable heading which consists of or includes the word ‘ingredients’. It shall include all the ingredients of the food, in descending order of weight, as recorded at the time of their use in the manufacture of the food.

Without prejudice to Article 21, food additives and food enzymes other than those specified in point (b) of Article 20 belonging to one of the categories listed in this Part must be designated by the name of that category, followed by their specific name or, if appropriate, E number. If an ingredient belongs to more than one of the categories, the category appropriate to the principal function in the case of the food in question shall be indicated.

**See also**
[REGULATION (EU) No 1169/2011 SECTION 2 and ANNEX VI Part C](https://eur-lex.europa.eu/legal-content/EN/TXT/HTML/?uri=CELEX:02011R1169-20180101#id-f64fcae2-6a15-431a-9096-6b259cc1c634)

**Comment by filipecarneiro** [comment]
Ingredient category format:
   "category (ingredient1, ingredient2)" or
   "category: ingredient1, ingredient2" or
   "category e-number1 e-number2"

**Comment by susedv** [comment]
Thank you, I was missing the option "category: ingredient1, ingredient2" and now it's working as expected without my workaround code.
