### ISSUE TITLE
Implement Automatic Dark/Light Mode

### ISSUE THREAD

**Issue by Adelino** [filipecarneiro/ELabel#21]
First of all, I would like to congratulate on your comprehensive solution for e-labels and thank you for making it available as MIT license on Github. 
I've just deployed it using docker, it was a breeze to get it online and very intuitive to configure. I'm just starting to trying it out, and still need to check one of the latest features, custom css.

I'm a rusted .net developer and I've a brand of wines in Portugal from the Vinho Verde region, so I'm very interested in deploying this to production in my company, and contribute as much as I can to the project.

**Is your feature request related to a problem? Please describe.**
Implement Automatic Dark/Light Mode

**Describe the solution you'd like**
 - Initialize data-bs-theme attribute as auto
 - Add javascript to detect user prefered color scheme
 
I've tried this in the browser and it works.

```
(function () {
  const htmlElement = document.querySelector("html")
if(htmlElement.getAttribute("data-bs-theme") === 'auto') {
  if (window.matchMedia && window.matchMedia('(prefers-color-scheme: dark)').matches) {
      document.documentElement.setAttribute('data-bs-theme', 'dark');
      console.log('switching to dark theme');
  }

  if (window.matchMedia && window.matchMedia('(prefers-color-scheme: light)').matches) {
      document.documentElement.setAttribute('data-bs-theme', 'light');
      console.log('switching to light theme');
  }
}
})();
```

**Describe alternatives you've considered**
As an alternative to automatic theme selection, another option would be to let the user define a default theme, dark or light. My assumption here, is that most of the users will prefer to use light, since most brands communicate that way.

**Additional context**
no need, I think

I will try to setup a development environment and send a PR, if you think this feature makes sense.

**Comment by filipecarneiro** [comment]
That’s cool, Adelino!

I don't have a strong proficiency in JavaScript, but that appears to be well-done.

Make the PR and I’ll help testing.

Thank you!

**Comment by filipecarneiro** [comment]
JavaScript code review by ChatGPT ;)

```
(function () {
  // Select the <html> element
  const htmlElement = document.querySelector("html");

  // Error handling for null htmlElement
  if (!htmlElement) {
    console.error("HTML element not found");
    return;
  }

  // Check if the data-bs-theme attribute is set to 'auto'
  if (htmlElement.getAttribute("data-bs-theme") === 'auto') {
    // Check user's color scheme preference
    if (window.matchMedia && window.matchMedia('(prefers-color-scheme: dark)').matches) {
      // Switch to dark theme
      switchTheme('dark');
    }

    // Check user's color scheme preference
    if (window.matchMedia && window.matchMedia('(prefers-color-scheme: light)').matches) {
      // Switch to light theme
      switchTheme('light');
    }
  }

  // Function to switch theme
  function switchTheme(theme) {
    document.documentElement.setAttribute('data-bs-theme', theme);
    console.log(`Switching to ${theme} theme`);
  }
})();

```

Check if this makes sense to you.

**Comment by filipecarneiro** [comment]
Emulating prefers-color-scheme in [DevTools](https://web.dev/articles/prefers-color-scheme#debugging_and_testing_dark_mode)  works fine with this test label:

https://qr.doutorpc.net/l/GR904-2015
